CREATE TABLE IF NOT EXISTS users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY,
    email    varchar(50) NOT NULL,
    login    varchar(30) NOT NULL,
    name     varchar(20) NOT NULL,
    birthday date        NOT NULL,
    CONSTRAINT users_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user_friends
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   INTEGER REFERENCES users (id) ON DELETE CASCADE,
    friend_id INTEGER REFERENCES users (id) ON DELETE CASCADE
    CONSTRAINT chk_different_user CHECK (user_id <> friend_id)
);

CREATE TABLE IF NOT EXISTS films
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name        varchar(20) NOT NULL,
    description text        NOT NULL,
    releaseDate date        NOT NULL,
    duration    long,
    rating      varchar(20),
    CONSTRAINT film_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS film_genres
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id INTEGER REFERENCES films (id) ON DELETE CASCADE,
    genre   varchar(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS film_likes
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id INTEGER REFERENCES films (id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users (id) ON DELETE CASCADE
);