CREATE TABLE IF NOT EXISTS users (
                       id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                       email varchar(50) NOT null,
                       login varchar(30) NOT null,
                       name varchar(20) NOT null,
                       birthday date NOT null,
                       CONSTRAINT users_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS friend_status(
                              id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                              status varchar(20) UNIQUE,
                              CONSTRAINT status_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user_friends(
                             id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
                             friend_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
                             status_id INTEGER REFERENCES friend_status (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS rating(
                       id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                       rating varchar(20) UNIQUE,
                       CONSTRAINT rating_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS films (
                       id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                       name varchar,
                       description text,
                       releaseDate date,
                       duration time,
                       rating_id INTEGER REFERENCES rating(id) ON DELETE RESTRICT,
                       CONSTRAINT film_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS genre(
                      id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                      genre varchar(20) UNIQUE,
                      CONSTRAINT genre_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS film_genre(
                           id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           film_id INTEGER REFERENCES films (id) ON DELETE CASCADE,
                           genre_id INTEGER REFERENCES genre (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS film_likes(
                           id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           film_id INTEGER REFERENCES films (id) ON DELETE CASCADE,
                           user_id INTEGER REFERENCES users (id) ON DELETE CASCADE
);